import {
  BriefcaseBusiness,
  Calculator,
  Cog,
  ConciergeBell,
  Cpu,
  DraftingCompass,
  Factory,
  FlaskConical,
  GraduationCap,
  HandHeart,
  HardHat,
  HeartPulse,
  HouseHeart,
  Landmark,
  Rocket,
  Ticket,
  Truck,
  type LucideIcon,
} from "lucide-react";

/** Shared sector slug → icon map, used by the sectors hub and individual sector pages. */
export const sectorIcons: Record<string, LucideIcon> = {
  "hr-company-for-startups-and-scale-ups-in-the-uk": Rocket,
  "hr-company-for-professional-services-in-the-uk": BriefcaseBusiness,
  "hr-company-for-healthcare-in-the-uk": HeartPulse,
  "hr-company-for-life-sciences-in-the-uk": FlaskConical,
  "hr-company-for-it-in-the-uk": Cpu,
  "hr-company-for-financial-services-in-the-uk": Landmark,
  "hr-company-for-accountants-in-the-uk": Calculator,
  "hr-company-for-architects-in-the-uk": DraftingCompass,
  "hr-company-for-care-homes-in-the-uk": HouseHeart,
  "hr-company-for-charity-in-the-uk": HandHeart,
  "hr-company-for-construction-in-the-uk": HardHat,
  "hr-company-for-distribution-in-the-uk": Truck,
  "hr-company-for-education-in-the-uk": GraduationCap,
  "hr-company-for-engineers-in-the-uk": Cog,
  "hr-company-for-leisure-in-the-uk": Ticket,
  "hr-company-for-manufacturers-in-the-uk": Factory,
  "hr-company-for-hospitality-in-the-uk": ConciergeBell,
};
