import {
  BriefcaseBusiness,
  Calculator,
  Cog,
  ConciergeBell,
  Cpu,
  DraftingCompass,
  Factory,
  FlaskConical,
  GraduationCap,
  HandHeart,
  HardHat,
  HeartPulse,
  HouseHeart,
  Landmark,
  Rocket,
  Ticket,
  Truck,
  type LucideIcon,
} from "lucide-react";

/** Shared sector slug → icon map, used by the sectors hub and individual sector pages. */
export const sectorIcons: Record<string, LucideIcon> = {
  "startups-scale-ups": Rocket,
  "professional-services": BriefcaseBusiness,
  "health-care": HeartPulse,
  "life-sciences": FlaskConical,
  technology: Cpu,
  "financial-services": Landmark,
  accountants: Calculator,
  architects: DraftingCompass,
  "care-homes": HouseHeart,
  charity: HandHeart,
  construction: HardHat,
  distribution: Truck,
  education: GraduationCap,
  engineers: Cog,
  leisure: Ticket,
  manufacturers: Factory,
  hospitality: ConciergeBell,
};
