/**
 * Full 72-rule permanent redirect registry, extracted verbatim from the
 * "Redirects" sheet of docs/Apex_HR_Master_Sitemap_and_URL_Register.xlsx
 * (cross-checked: 72 rows, all Status "Redirected"). Consumed by
 * next.config.ts's `redirects()` and validated by
 * tests/unit/redirects.test.ts. Do not add a redirect rule here that
 * isn't governed by that register — see CLAUDE.md section 19.
 *
 * A further 44 rules were added in SEO audit Phase 2 Batch 3
 * (docs/URL-DECISION-REGISTER.md D-015): every category-location
 * combination page that covered exactly one child service at that location
 * redirects permanently to that one child's own service-location page,
 * resolving the keyword cannibalisation identified in the category-location
 * decision table. These sources are no longer generated as pages — see the
 * raised category/location curation threshold in
 * src/config/service-locations.ts (a category-location page now needs at
 * least two curated child services to exist at all). The two locations that
 * do curate two services in the same category (Outsourced HR Services in
 * Worcester, Recruitment & Talent Acquisition in Liverpool) keep their
 * category-location pages live and are not redirected.
 */

export interface RedirectRule {
  source: string;
  destination: string;
  reason: string;
}

export const redirectRules: RedirectRule[] = [
  { source: "/services/recruitment-talent-and-acuqisition/", destination: "/services/recruitment-and-talent-acquisition-firm-in-the-uk/", reason: "Corrected misspelling in service URL" },
  { source: "/services/organisation-deevelopment-and-change-movement/", destination: "/services/organisation-development-and-change-management-firm-in-the-uk/", reason: "Corrected misspelling in service URL" },
  { source: "/services/leadership-and-leadership-development/", destination: "/services/learning-and-leadership-development-firm-in-the-uk/", reason: "Corrected misspelling in service URL" },
  { source: "/insights/organization-development/", destination: "/insights/organisation-development/", reason: "Corrected insight category spelling or path format" },
  { source: "/insights/performance/talent/", destination: "/insights/performance-talent/", reason: "Corrected insight category spelling or path format" },
  { source: "/industries/", destination: "/sector/", reason: "Sector is the approved canonical taxonomy" },
  { source: "/industries/startups-scale-ups/", destination: "/sector/hr-company-for-startups-and-scale-ups-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/professional-services/", destination: "/sector/hr-company-for-professional-services-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/health-care/", destination: "/sector/hr-company-for-healthcare-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/life-sciences/", destination: "/sector/hr-company-for-life-sciences-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/technology/", destination: "/sector/hr-company-for-it-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/financial-services/", destination: "/sector/hr-company-for-financial-services-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/accountants/", destination: "/sector/hr-company-for-accountants-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/architects/", destination: "/sector/hr-company-for-architects-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/care-homes/", destination: "/sector/hr-company-for-care-homes-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/charity/", destination: "/sector/hr-company-for-charity-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/constructions/", destination: "/sector/hr-company-for-construction-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/destributors/", destination: "/sector/hr-company-for-distribution-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/distribution/", destination: "/sector/hr-company-for-distribution-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/education/", destination: "/sector/hr-company-for-education-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/engineers/", destination: "/sector/hr-company-for-engineers-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/leisure/", destination: "/sector/hr-company-for-leisure-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/manufacturers/", destination: "/sector/hr-company-for-manufacturers-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/industries/hospitality/", destination: "/sector/hr-company-for-hospitality-in-the-uk/", reason: "Replace retired industries taxonomy with sector" },
  { source: "/sector/constructions/", destination: "/sector/hr-company-for-construction-in-the-uk/", reason: "Correct spelling and singular sector slug" },
  { source: "/sector/destributors/", destination: "/sector/hr-company-for-distribution-in-the-uk/", reason: "Correct misspelled sector label and slug" },
  { source: "/contacts/", destination: "/contact/", reason: "Use the approved singular Contact route" },
  { source: "/locations/nothingham/", destination: "/locations/nottingham/", reason: "Correct misspelled location slug" },
  { source: "/locations/worchester/", destination: "/locations/worcester/", reason: "Correct misspelled location slug" },
  { source: "/locations/standfordshire/", destination: "/locations/staffordshire/", reason: "Correct misspelled location slug" },
  { source: "/services/talent-acquisition-recruitment/", destination: "/services/recruitment-and-talent-acquisition-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/talent-acquisition-recruitment/executive-search/", destination: "/services/executive-search-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/talent-acquisition-recruitment/permanent-recruitment/", destination: "/services/permanent-recruitment-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/talent-acquisition-recruitment/contract-staffing/", destination: "/services/contract-staffing-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/talent-acquisition-recruitment/recruitment-process-outsourcing/", destination: "/services/recruitment-process-outsourcing-rpo-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/organisation-development-change/", destination: "/services/organisation-development-and-change-management-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/organisation-development-change/organisation-design/", destination: "/services/organisation-design-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/organisation-development-change/culture-transformation/", destination: "/services/culture-transformation-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/organisation-development-change/change-management/", destination: "/services/change-management-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/learning-development/", destination: "/services/learning-and-leadership-development-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/learning-development/leadership-development/", destination: "/services/leadership-and-management-training-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/learning-development/management-training/", destination: "/services/leadership-and-management-training-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/learning-development/executive-coaching/", destination: "/services/executive-coaching-and-360-feedback-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/learning-development/learning-strategy/", destination: "/services/learning-strategy-and-capability-development-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/performance-talent-management/performance-management/", destination: "/services/performance-management-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/performance-talent-management/succession-planning/", destination: "/services/succession-planning-and-talent-mapping-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/performance-talent-management/competency-frameworks/", destination: "/services/competency-frameworks-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/compensation-benefits/", destination: "/services/compensation-reward-and-benefits-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/compensation-benefits/salary-benchmarking/", destination: "/services/salary-benchmarking-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/compensation-benefits/job-evaluation/", destination: "/services/job-evaluation-and-pay-structures-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/compensation-benefits/reward-strategy/", destination: "/services/reward-strategy-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/compensation-benefits/pay-equity/", destination: "/services/pay-equity-and-pay-gap-reporting-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/compensation-benefits/employee-benefits/", destination: "/services/employee-benefits-consulting-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/compensation-benefits/payroll-advisory/", destination: "/services/payroll-advisory-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/employee-experience-engagement/employee-engagement/", destination: "/services/employee-experience-strategy-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/employee-experience-engagement/engagement-surveys/", destination: "/services/employee-engagement-surveys-and-action-planning-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/employee-experience-engagement/employee-value-proposition/", destination: "/services/employer-branding-and-employee-value-proposition-evp-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/employee-experience-engagement/employer-brand-strategy/", destination: "/services/employer-branding-and-employee-value-proposition-evp-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/employee-experience-engagement/wellbeing/", destination: "/services/workplace-wellbeing-and-mental-health-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/employee-experience-engagement/dei-strategy/", destination: "/services/diversity-equity-and-inclusion-dei-consulting-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/hr-technology-people-analytics/", destination: "/services/hr-technology-and-people-analytics-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/hr-technology-people-analytics/hris-implementation/", destination: "/services/hris-implementation-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/hr-technology-people-analytics/hr-software-selection/", destination: "/services/hr-software-selection-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/hr-technology-people-analytics/people-analytics/", destination: "/services/people-analytics-and-hr-dashboards-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/hr-technology-people-analytics/digital-hr-transformation/", destination: "/services/digital-hr-transformation-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/talent-strategy-workforce-planning/", destination: "/services/strategic-hr-and-workforce-advisory-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/talent-strategy-workforce-planning/strategic-workforce-planning/", destination: "/services/strategic-workforce-planning-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/people-strategy-advisory/", destination: "/services/strategic-hr-and-workforce-advisory-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/people-strategy-advisory/people-strategy/", destination: "/services/people-strategy-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/people-strategy-advisory/fractional-chro/", destination: "/services/fractional-hr-director-chief-people-officer-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/people-strategy-advisory/startup-hr/", destination: "/services/hr-support-for-small-businesses-and-startups-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },
  { source: "/services/people-strategy-advisory/scale-up-hr/", destination: "/services/hr-support-for-small-businesses-and-startups-firm-in-the-uk/", reason: "Consolidate competing nested taxonomy into canonical flat service URL" },

  // SEO audit Phase 2 Batch 3 — 44 single-child category-location redirects
  // (docs/URL-DECISION-REGISTER.md D-015). See the module doc comment above.
  { source: "/services/recruitment-talent-acquisition-london/", destination: "/services/executive-search-firm-in-the-uk-london/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Executive Search (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/compensation-reward-and-benefits-london/", destination: "/services/salary-benchmarking-firm-in-the-uk-london/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Compensation, Reward & Benefits and Salary Benchmarking (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/employee-experience-and-engagement-london/", destination: "/services/employer-branding-and-employee-value-proposition-evp-firm-in-the-uk-london/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Employee Experience & Engagement and Employer Branding & Employee Value Proposition (EVP) (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-manchester/", destination: "/services/permanent-recruitment-firm-in-the-uk-manchester/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Permanent Recruitment (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/hr-technology-and-people-analytics-manchester/", destination: "/services/hris-implementation-firm-in-the-uk-manchester/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between HR Technology & People Analytics and HRIS Implementation (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/strategic-hr-and-workforce-advisory-manchester/", destination: "/services/strategic-workforce-planning-firm-in-the-uk-manchester/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Strategic HR & Workforce Advisory and Strategic Workforce Planning (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-birmingham/", destination: "/services/permanent-recruitment-firm-in-the-uk-birmingham/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Permanent Recruitment (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/outsourced-hr-services-birmingham/", destination: "/services/hr-compliance-audit-firm-in-the-uk-birmingham/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Outsourced HR Services and HR Compliance Audit (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/strategic-hr-and-workforce-advisory-birmingham/", destination: "/services/strategic-workforce-planning-firm-in-the-uk-birmingham/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Strategic HR & Workforce Advisory and Strategic Workforce Planning (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/compensation-reward-and-benefits-leeds/", destination: "/services/salary-benchmarking-firm-in-the-uk-leeds/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Compensation, Reward & Benefits and Salary Benchmarking (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-leeds/", destination: "/services/permanent-recruitment-firm-in-the-uk-leeds/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Permanent Recruitment (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/hr-technology-and-people-analytics-leeds/", destination: "/services/hris-implementation-firm-in-the-uk-leeds/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between HR Technology & People Analytics and HRIS Implementation (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-bristol/", destination: "/services/permanent-recruitment-firm-in-the-uk-bristol/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Permanent Recruitment (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/compensation-reward-and-benefits-bristol/", destination: "/services/salary-benchmarking-firm-in-the-uk-bristol/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Compensation, Reward & Benefits and Salary Benchmarking (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/outsourced-hr-services-bristol/", destination: "/services/hr-support-for-small-businesses-and-startups-firm-in-the-uk-bristol/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Outsourced HR Services and HR Support for Small Businesses & Startups (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-edinburgh/", destination: "/services/executive-search-firm-in-the-uk-edinburgh/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Executive Search (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/compensation-reward-and-benefits-edinburgh/", destination: "/services/salary-benchmarking-firm-in-the-uk-edinburgh/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Compensation, Reward & Benefits and Salary Benchmarking (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/outsourced-hr-services-edinburgh/", destination: "/services/hr-compliance-audit-firm-in-the-uk-edinburgh/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Outsourced HR Services and HR Compliance Audit (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-glasgow/", destination: "/services/permanent-recruitment-firm-in-the-uk-glasgow/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Permanent Recruitment (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/strategic-hr-and-workforce-advisory-glasgow/", destination: "/services/strategic-workforce-planning-firm-in-the-uk-glasgow/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Strategic HR & Workforce Advisory and Strategic Workforce Planning (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/outsourced-hr-services-glasgow/", destination: "/services/hr-compliance-audit-firm-in-the-uk-glasgow/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Outsourced HR Services and HR Compliance Audit (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-nottingham/", destination: "/services/permanent-recruitment-firm-in-the-uk-nottingham/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Permanent Recruitment (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/outsourced-hr-services-nottingham/", destination: "/services/hr-compliance-audit-firm-in-the-uk-nottingham/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Outsourced HR Services and HR Compliance Audit (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/strategic-hr-and-workforce-advisory-nottingham/", destination: "/services/strategic-workforce-planning-firm-in-the-uk-nottingham/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Strategic HR & Workforce Advisory and Strategic Workforce Planning (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-newcastle/", destination: "/services/permanent-recruitment-firm-in-the-uk-newcastle/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Permanent Recruitment (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/outsourced-hr-services-newcastle/", destination: "/services/hr-support-for-small-businesses-and-startups-firm-in-the-uk-newcastle/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Outsourced HR Services and HR Support for Small Businesses & Startups (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/compensation-reward-and-benefits-newcastle/", destination: "/services/salary-benchmarking-firm-in-the-uk-newcastle/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Compensation, Reward & Benefits and Salary Benchmarking (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-warwickshire/", destination: "/services/permanent-recruitment-firm-in-the-uk-warwickshire/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Permanent Recruitment (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/performance-and-talent-management-warwickshire/", destination: "/services/competency-frameworks-firm-in-the-uk-warwickshire/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Performance & Talent Management and Competency Frameworks (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/strategic-hr-and-workforce-advisory-warwickshire/", destination: "/services/strategic-workforce-planning-firm-in-the-uk-warwickshire/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Strategic HR & Workforce Advisory and Strategic Workforce Planning (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-worcester/", destination: "/services/permanent-recruitment-firm-in-the-uk-worcester/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Permanent Recruitment (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-yorkshire/", destination: "/services/permanent-recruitment-firm-in-the-uk-yorkshire/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Permanent Recruitment (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/strategic-hr-and-workforce-advisory-yorkshire/", destination: "/services/strategic-workforce-planning-firm-in-the-uk-yorkshire/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Strategic HR & Workforce Advisory and Strategic Workforce Planning (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/compensation-reward-and-benefits-yorkshire/", destination: "/services/salary-benchmarking-firm-in-the-uk-yorkshire/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Compensation, Reward & Benefits and Salary Benchmarking (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-staffordshire/", destination: "/services/permanent-recruitment-firm-in-the-uk-staffordshire/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Permanent Recruitment (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/employment-law-and-employee-relations-staffordshire/", destination: "/services/redundancy-and-restructuring-support-firm-in-the-uk-staffordshire/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Employment Law & Employee Relations and Redundancy & Restructuring Support (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/outsourced-hr-services-staffordshire/", destination: "/services/hr-compliance-audit-firm-in-the-uk-staffordshire/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Outsourced HR Services and HR Compliance Audit (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/outsourced-hr-services-liverpool/", destination: "/services/hr-compliance-audit-firm-in-the-uk-liverpool/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Outsourced HR Services and HR Compliance Audit (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-oxford/", destination: "/services/executive-search-firm-in-the-uk-oxford/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Executive Search (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/strategic-hr-and-workforce-advisory-oxford/", destination: "/services/strategic-workforce-planning-firm-in-the-uk-oxford/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Strategic HR & Workforce Advisory and Strategic Workforce Planning (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/compensation-reward-and-benefits-oxford/", destination: "/services/salary-benchmarking-firm-in-the-uk-oxford/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Compensation, Reward & Benefits and Salary Benchmarking (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/recruitment-talent-acquisition-leicester/", destination: "/services/permanent-recruitment-firm-in-the-uk-leicester/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Recruitment & Talent Acquisition and Permanent Recruitment (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/outsourced-hr-services-leicester/", destination: "/services/hr-compliance-audit-firm-in-the-uk-leicester/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Outsourced HR Services and HR Compliance Audit (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
  { source: "/services/strategic-hr-and-workforce-advisory-leicester/", destination: "/services/strategic-workforce-planning-firm-in-the-uk-leicester/", reason: "Category-location page redirected to its single child service-location page to resolve cannibalisation between Strategic HR & Workforce Advisory and Strategic Workforce Planning (SEO audit Phase 2 Batch 3, docs/URL-DECISION-REGISTER.md D-015)" },
];
