import type { ContentFaqItem } from "@/types/content";

/**
 * Original first-draft talent-acquisition-by-role content. The 62
 * slugs/titles below are taken verbatim from the "Talent acquisition role"
 * rows (Route Family) in the Master Routes sheet of
 * docs/Apex_HR_Master_Sitemap_and_URL_Register.xlsx — all 62 are Confirmed
 * — cross-checked against CLAUDE.md's "62 role pages" reference. Do not
 * add, remove or reword a role name without checking that sheet first.
 *
 * Per this phase's talent-acquisition rules: no candidate availability,
 * salary data, placement times or existing candidate pool is claimed for
 * any role, and content is informational, not regulated career advice.
 */

export interface TalentRoleContent {
  slug: string;
  title: string;
  roleFamily: string;
  metaDescription: string;
  overview: string;
  hiringChallenges: string[];
  skillsSought: string[];
  recruitmentApproach: string;
  relatedSectorSlugs: string[];
  relatedServiceSlugs: string[];
  faqs: ContentFaqItem[];
}

const genericFaq = (title: string): ContentFaqItem => ({
  id: "availability",
  question: `Can Apex HR guarantee candidates are available for ${title.toLowerCase()} roles?`,
  answer: "No specific candidate availability, timeline or salary outcome is guaranteed. Apex HR runs a structured search appropriate to the role and current market conditions.",
});

export const talentRoleContent: TalentRoleContent[] = [
  // --- Executive, senior leadership & management ---
  {
    slug: "chief-executives-senior-officials",
    title: "Chief executives and senior officials",
    roleFamily: "Executive & Senior Leadership",
    metaDescription: "Recruitment support for chief executive and senior official hires, using an executive search approach.",
    overview: "Chief executive and senior official appointments set the direction for an organisation, making search rigour and confidentiality especially important.",
    hiringChallenges: ["A small, often passive candidate pool", "High organisational impact if the appointment is wrong"],
    skillsSought: ["Strategic leadership track record", "Stakeholder and board management", "Sector or organisational context relevant to the role"],
    recruitmentApproach: "Typically run as a confidential executive search, with structured assessment against a leadership brief.",
    relatedSectorSlugs: ["hr-company-for-professional-services-in-the-uk", "hr-company-for-financial-services-in-the-uk"],
    relatedServiceSlugs: ["executive-search-firm-in-the-uk", "fractional-hr-director-chief-people-officer-firm-in-the-uk"],
    faqs: [genericFaq("chief executives and senior officials")],
  },
  {
    slug: "marketing-sales-advertising-directors",
    title: "Marketing, sales and advertising directors",
    roleFamily: "Executive & Senior Leadership",
    metaDescription: "Recruitment support for marketing, sales and advertising director hires.",
    overview: "These director-level roles combine commercial strategy with team leadership, and hiring well depends on assessing both.",
    hiringChallenges: ["Balancing commercial track record against leadership capability", "Competitive market for senior commercial talent"],
    skillsSought: ["Commercial strategy and delivery track record", "Team leadership experience", "Brand or market-specific expertise where relevant"],
    recruitmentApproach: "Usually combines targeted search with structured assessment of commercial and leadership capability.",
    relatedSectorSlugs: ["hr-company-for-it-in-the-uk", "hr-company-for-professional-services-in-the-uk"],
    relatedServiceSlugs: ["executive-search-firm-in-the-uk", "permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("marketing, sales and advertising directors")],
  },
  {
    slug: "consultancy-directors",
    title: "Directors in consultancy services",
    roleFamily: "Executive & Senior Leadership",
    metaDescription: "Recruitment support for consultancy director hires across professional services firms.",
    overview: "Consultancy director roles depend heavily on client relationships and technical credibility, both of which need careful assessment.",
    hiringChallenges: ["Assessing client relationship strength alongside technical skill", "Confidentiality around a competitor's client base"],
    skillsSought: ["Client relationship management", "Technical or domain credibility", "Business development track record"],
    recruitmentApproach: "Typically a confidential, targeted search given the seniority and client-sensitivity of the role.",
    relatedSectorSlugs: ["hr-company-for-professional-services-in-the-uk"],
    relatedServiceSlugs: ["executive-search-firm-in-the-uk"],
    faqs: [genericFaq("directors in consultancy services")],
  },
  {
    slug: "creative-industry-managers-directors",
    title: "Managers and directors in the creative industries",
    roleFamily: "Executive & Senior Leadership",
    metaDescription: "Recruitment support for management and director-level hires in creative industry businesses.",
    overview: "Creative leadership roles need a balance of creative credibility and commercial or operational management skill.",
    hiringChallenges: ["Assessing creative judgement alongside management ability", "Smaller, reputation-led talent networks"],
    skillsSought: ["Creative or portfolio credibility", "Team and studio management", "Commercial and client awareness"],
    recruitmentApproach: "Search often draws on portfolio review alongside structured leadership assessment.",
    relatedSectorSlugs: ["hr-company-for-architects-in-the-uk", "hr-company-for-professional-services-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "executive-search-firm-in-the-uk"],
    faqs: [genericFaq("managers and directors in the creative industries")],
  },
  {
    slug: "healthcare-practice-managers",
    title: "Health care practice managers",
    roleFamily: "Executive & Senior Leadership",
    metaDescription: "Recruitment support for healthcare practice manager hires.",
    overview: "Practice managers run the operational and administrative backbone of healthcare settings, requiring both management and sector-specific knowledge.",
    hiringChallenges: ["Sector-specific regulatory and operational knowledge", "Balancing clinical-team liaison with operational management"],
    skillsSought: ["Healthcare operations management", "Regulatory and compliance awareness", "Team leadership"],
    recruitmentApproach: "Assessment typically covers both operational management skill and healthcare-sector familiarity.",
    relatedSectorSlugs: ["hr-company-for-healthcare-in-the-uk", "hr-company-for-care-homes-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("health care practice managers")],
  },
  {
    slug: "care-managers-proprietors",
    title: "Residential, day and domiciliary care managers and proprietors",
    roleFamily: "Executive & Senior Leadership",
    metaDescription: "Recruitment support for residential, day and domiciliary care management hires.",
    overview: "Care management roles carry significant regulatory and safeguarding responsibility alongside day-to-day operational leadership.",
    hiringChallenges: ["Regulatory and registration requirements specific to care settings", "Demand for experienced care leadership across the sector"],
    skillsSought: ["Care sector management experience", "Regulatory and safeguarding knowledge", "Staff leadership in demanding roles"],
    recruitmentApproach: "Assessment focuses on care-sector management experience alongside regulatory awareness.",
    relatedSectorSlugs: ["hr-company-for-care-homes-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "hr-compliance-audit-firm-in-the-uk"],
    faqs: [genericFaq("residential, day and domiciliary care managers and proprietors")],
  },
  {
    slug: "storage-warehousing-managers",
    title: "Managers in storage and warehousing",
    roleFamily: "Executive & Senior Leadership",
    metaDescription: "Recruitment support for storage and warehousing management hires.",
    overview: "Warehousing management roles combine operational efficiency with people leadership across often large, shift-based teams.",
    hiringChallenges: ["Operational and logistics expertise", "Managing large, shift-based teams"],
    skillsSought: ["Warehouse or logistics operations management", "Health and safety leadership", "Team and shift management"],
    recruitmentApproach: "Assessment covers operational track record alongside people-management capability at scale.",
    relatedSectorSlugs: ["hr-company-for-distribution-in-the-uk", "hr-company-for-manufacturers-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "recruitment-process-outsourcing-rpo-firm-in-the-uk"],
    faqs: [genericFaq("managers in storage and warehousing")],
  },
  {
    slug: "office-managers",
    title: "Office managers",
    roleFamily: "Executive & Senior Leadership",
    metaDescription: "Recruitment support for office manager hires across a range of business types.",
    overview: "Office managers are often the operational backbone of a business, requiring broad capability across administration, facilities and people support.",
    hiringChallenges: ["Broad skill requirements across a generalist role", "Assessing organisational and prioritisation skill"],
    skillsSought: ["Organisational and administrative capability", "Facilities and supplier coordination", "Discretion and reliability"],
    recruitmentApproach: "Assessment typically covers practical organisational skills alongside cultural fit with the team.",
    relatedSectorSlugs: ["hr-company-for-professional-services-in-the-uk", "hr-company-for-charity-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("office managers")],
  },
  {
    slug: "cleaning-housekeeping-managers-supervisors",
    title: "Cleaning and housekeeping managers and supervisors",
    roleFamily: "Executive & Senior Leadership",
    metaDescription: "Recruitment support for cleaning and housekeeping management and supervisory hires.",
    overview: "These roles combine operational standards management with supervision of often large, part-time or shift-based teams.",
    hiringChallenges: ["Managing large or part-time shift-based teams", "Maintaining consistent service standards across sites"],
    skillsSought: ["Team supervision experience", "Operational standards management", "Scheduling and resource planning"],
    recruitmentApproach: "Assessment focuses on supervisory experience and operational consistency across sites.",
    relatedSectorSlugs: ["hr-company-for-hospitality-in-the-uk", "hr-company-for-leisure-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "recruitment-process-outsourcing-rpo-firm-in-the-uk"],
    faqs: [genericFaq("cleaning and housekeeping managers and supervisors")],
  },
  {
    slug: "health-safety-managers-officers",
    title: "Health and safety managers and officers",
    roleFamily: "Executive & Senior Leadership",
    metaDescription: "Recruitment support for health and safety manager and officer hires.",
    overview: "Health and safety roles carry direct compliance responsibility, making relevant qualifications and practical experience essential to assess.",
    hiringChallenges: ["Verifying relevant qualifications and accreditation", "Sector-specific safety knowledge requirements"],
    skillsSought: ["Recognised health and safety qualifications", "Sector-relevant risk assessment experience", "Practical, on-site credibility"],
    recruitmentApproach: "Assessment includes verification of relevant qualifications alongside practical, sector-specific experience.",
    relatedSectorSlugs: ["hr-company-for-construction-in-the-uk", "hr-company-for-manufacturers-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "hr-compliance-audit-firm-in-the-uk"],
    faqs: [genericFaq("health and safety managers and officers")],
  },
  {
    slug: "education-advisers-school-inspectors",
    title: "Education advisers and school inspectors",
    roleFamily: "Executive & Senior Leadership",
    metaDescription: "Recruitment support for education adviser and school inspector hires.",
    overview: "These roles require deep education-sector expertise and credibility with school leadership and governance bodies.",
    hiringChallenges: ["Requirement for recognised education-sector credibility", "Small, specialist candidate pool"],
    skillsSought: ["Education leadership or inspection background", "Regulatory and curriculum knowledge", "Stakeholder engagement skills"],
    recruitmentApproach: "Search typically draws on education-sector networks and structured assessment of relevant experience.",
    relatedSectorSlugs: ["hr-company-for-education-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "executive-search-firm-in-the-uk"],
    faqs: [genericFaq("education advisers and school inspectors")],
  },

  // --- Sales & business development ---
  {
    slug: "business-sales-executives",
    title: "Business sales executives",
    roleFamily: "Sales & Business Development",
    metaDescription: "Recruitment support for business sales executive hires.",
    overview: "Sales executive roles are typically assessed on a track record of delivering against commercial targets and building client relationships.",
    hiringChallenges: ["Assessing genuine sales track record versus inflated claims", "Competitive market for proven sales performers"],
    skillsSought: ["Demonstrable sales track record", "Client relationship and pipeline management", "Resilience and target focus"],
    recruitmentApproach: "Assessment typically includes structured discussion of track record alongside role-specific scenarios.",
    relatedSectorSlugs: ["hr-company-for-it-in-the-uk", "hr-company-for-professional-services-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("business sales executives")],
  },
  {
    slug: "sales-business-development-managers",
    title: "Sales accounts and business development managers",
    roleFamily: "Sales & Business Development",
    metaDescription: "Recruitment support for sales accounts and business development manager hires.",
    overview: "These roles blend account management with new business development, requiring both relationship management and commercial drive.",
    hiringChallenges: ["Balancing account management and new business skill sets", "Verifying commercial impact claims"],
    skillsSought: ["Account management experience", "New business development track record", "Sector or market familiarity"],
    recruitmentApproach: "Assessment covers both existing account performance and evidence of new business generation.",
    relatedSectorSlugs: ["hr-company-for-it-in-the-uk", "hr-company-for-distribution-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("sales accounts and business development managers")],
  },
  {
    slug: "buyers-procurement-officers",
    title: "Buyers and procurement officers",
    roleFamily: "Sales & Business Development",
    metaDescription: "Recruitment support for buyer and procurement officer hires.",
    overview: "Procurement roles require strong negotiation skill and category or supplier-market knowledge relevant to the business.",
    hiringChallenges: ["Category-specific market knowledge requirements", "Assessing negotiation and cost-management skill"],
    skillsSought: ["Procurement or category management experience", "Negotiation and supplier management", "Analytical and cost-control skills"],
    recruitmentApproach: "Assessment focuses on relevant category experience and evidence of successful supplier negotiation.",
    relatedSectorSlugs: ["hr-company-for-manufacturers-in-the-uk", "hr-company-for-distribution-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("buyers and procurement officers")],
  },
  {
    slug: "market-research-interviewers",
    title: "Market research interviewers",
    roleFamily: "Sales & Business Development",
    metaDescription: "Recruitment support for market research interviewer hires.",
    overview: "These roles depend on strong communication skills and the ability to gather consistent, unbiased data from respondents.",
    hiringChallenges: ["Assessing interviewing consistency and objectivity", "Often flexible or part-time resourcing needs"],
    skillsSought: ["Strong verbal communication", "Attention to process and data accuracy", "Comfort with structured interview scripts"],
    recruitmentApproach: "Recruitment can be structured around fixed-term or flexible resourcing needs depending on project scope.",
    relatedSectorSlugs: ["hr-company-for-professional-services-in-the-uk"],
    relatedServiceSlugs: ["contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("market research interviewers")],
  },
  {
    slug: "brokers",
    title: "Brokers",
    roleFamily: "Sales & Business Development",
    metaDescription: "Recruitment support for broker hires across insurance, finance and related markets.",
    overview: "Broker roles depend on relationship management, market knowledge and, in many cases, relevant regulatory qualifications.",
    hiringChallenges: ["Verifying relevant regulatory qualifications", "Assessing existing client relationships appropriately and fairly"],
    skillsSought: ["Relevant regulatory or professional qualifications", "Client relationship management", "Market and product knowledge"],
    recruitmentApproach: "Assessment includes qualification verification alongside track record and relationship-management skill.",
    relatedSectorSlugs: ["hr-company-for-financial-services-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "executive-search-firm-in-the-uk"],
    faqs: [genericFaq("brokers")],
  },
  {
    slug: "insurance-underwriters",
    title: "Insurance underwriters",
    roleFamily: "Sales & Business Development",
    metaDescription: "Recruitment support for insurance underwriter hires.",
    overview: "Underwriting roles require sound risk judgement and, typically, relevant professional qualifications or progress toward them.",
    hiringChallenges: ["Verifying underwriting experience and qualification level", "Specialist lines requiring niche expertise"],
    skillsSought: ["Underwriting experience relevant to the class of business", "Risk assessment and analytical skill", "Relevant professional qualifications"],
    recruitmentApproach: "Assessment focuses on underwriting experience within the relevant class of business and risk appetite.",
    relatedSectorSlugs: ["hr-company-for-financial-services-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("insurance underwriters")],
  },

  // --- IT, data & digital ---
  {
    slug: "it-business-analysts-architects-systems-designers",
    title: "IT business analysts, architects and systems designers",
    roleFamily: "IT & Data",
    metaDescription: "Recruitment support for IT business analyst, architect and systems designer hires.",
    overview: "These roles sit between business and technical teams, requiring both technical depth and strong stakeholder communication.",
    hiringChallenges: ["Competitive market for experienced technical talent", "Assessing depth across both technical and business skills"],
    skillsSought: ["Relevant technical architecture or analysis experience", "Stakeholder communication", "Domain or industry familiarity"],
    recruitmentApproach: "Assessment typically includes technical discussion alongside evaluation of stakeholder and communication skills.",
    relatedSectorSlugs: ["hr-company-for-it-in-the-uk", "hr-company-for-financial-services-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("IT business analysts, architects and systems designers")],
  },
  {
    slug: "it-operations-technicians",
    title: "IT operations technicians",
    roleFamily: "IT & Data",
    metaDescription: "Recruitment support for IT operations technician hires.",
    overview: "Operations technician roles require solid technical grounding and reliability, often supporting business-critical infrastructure.",
    hiringChallenges: ["Verifying hands-on technical competence", "Shift or on-call resourcing considerations"],
    skillsSought: ["Relevant infrastructure or systems experience", "Troubleshooting under pressure", "Process discipline"],
    recruitmentApproach: "Assessment includes technical screening alongside practical, scenario-based discussion.",
    relatedSectorSlugs: ["hr-company-for-it-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("IT operations technicians")],
  },
  {
    slug: "it-user-support-technicians",
    title: "IT user support technicians",
    roleFamily: "IT & Data",
    metaDescription: "Recruitment support for IT user support technician hires.",
    overview: "Support technician roles combine technical troubleshooting with clear, patient communication with non-technical colleagues.",
    hiringChallenges: ["Balancing technical skill with customer service ability", "High-volume resourcing needs in larger organisations"],
    skillsSought: ["Technical troubleshooting ability", "Clear communication with non-technical users", "Ticketing and process discipline"],
    recruitmentApproach: "Assessment typically covers technical competence alongside communication and service orientation.",
    relatedSectorSlugs: ["hr-company-for-it-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "recruitment-process-outsourcing-rpo-firm-in-the-uk"],
    faqs: [genericFaq("IT user support technicians")],
  },
  {
    slug: "data-analysts",
    title: "Data analysts",
    roleFamily: "IT & Data",
    metaDescription: "Recruitment support for data analyst hires.",
    overview: "Data analyst roles increasingly span technical tooling, statistical reasoning and the ability to communicate insight clearly to non-technical audiences.",
    hiringChallenges: ["Highly competitive market for strong analytical talent", "Assessing genuine analytical rigour, not just tool familiarity"],
    skillsSought: ["Relevant analytical and tooling experience", "Statistical or quantitative reasoning", "Clear communication of insight"],
    recruitmentApproach: "Assessment typically includes a practical analytical exercise alongside discussion of past project work.",
    relatedSectorSlugs: ["hr-company-for-it-in-the-uk", "hr-company-for-financial-services-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "people-analytics-and-hr-dashboards-firm-in-the-uk"],
    faqs: [genericFaq("data analysts")],
  },
  {
    slug: "information-technology-trainers",
    title: "Information technology trainers",
    roleFamily: "IT & Data",
    metaDescription: "Recruitment support for information technology trainer hires.",
    overview: "IT trainer roles require both technical credibility and the ability to teach effectively across varying skill levels.",
    hiringChallenges: ["Combining technical depth with genuine training ability", "Often project-based or fluctuating demand"],
    skillsSought: ["Technical subject-matter expertise", "Training design and delivery experience", "Adaptability to audience skill level"],
    recruitmentApproach: "Assessment covers subject expertise alongside evidence of effective training delivery.",
    relatedSectorSlugs: ["hr-company-for-it-in-the-uk"],
    relatedServiceSlugs: ["contract-staffing-firm-in-the-uk", "learning-strategy-and-capability-development-firm-in-the-uk"],
    faqs: [genericFaq("information technology trainers")],
  },

  // --- Healthcare & care ---
  {
    slug: "generalist-medical-practitioners",
    title: "Generalist medical practitioners",
    roleFamily: "Healthcare & Care",
    metaDescription: "Recruitment support for generalist medical practitioner hires, subject to appropriate professional registration.",
    overview: "Generalist medical roles require verified professional registration and are typically in high demand across the healthcare sector.",
    hiringChallenges: ["Nationwide demand and competitive market", "Verifying professional registration and qualifications"],
    skillsSought: ["Relevant professional registration and qualifications", "Clinical experience appropriate to the setting", "Strong patient communication"],
    recruitmentApproach: "Recruitment process includes verification of registration and qualifications alongside standard HR screening.",
    relatedSectorSlugs: ["hr-company-for-healthcare-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("generalist medical practitioners")],
  },
  {
    slug: "specialist-medical-practitioners",
    title: "Specialist medical practitioners",
    roleFamily: "Healthcare & Care",
    metaDescription: "Recruitment support for specialist medical practitioner hires, subject to appropriate professional registration.",
    overview: "Specialist medical roles require verified registration in the relevant specialty and are often part of a highly competitive, specialised market.",
    hiringChallenges: ["Small, specialist candidate pools", "Verifying specialty-specific registration and accreditation"],
    skillsSought: ["Relevant specialty registration and accreditation", "Specialist clinical experience", "Team and departmental collaboration"],
    recruitmentApproach: "Search often draws on specialist networks alongside verification of registration and accreditation.",
    relatedSectorSlugs: ["hr-company-for-healthcare-in-the-uk"],
    relatedServiceSlugs: ["executive-search-firm-in-the-uk", "permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("specialist medical practitioners")],
  },
  {
    slug: "occupational-therapists",
    title: "Occupational therapists",
    roleFamily: "Healthcare & Care",
    metaDescription: "Recruitment support for occupational therapist hires, subject to appropriate professional registration.",
    overview: "Occupational therapy roles require relevant professional registration and experience appropriate to the care setting involved.",
    hiringChallenges: ["Verifying professional registration", "Setting-specific experience requirements"],
    skillsSought: ["Relevant professional registration", "Setting-appropriate clinical experience", "Person-centred communication"],
    recruitmentApproach: "Recruitment process includes registration verification alongside setting-specific experience review.",
    relatedSectorSlugs: ["hr-company-for-healthcare-in-the-uk", "hr-company-for-care-homes-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("occupational therapists")],
  },
  {
    slug: "speech-language-therapists",
    title: "Speech and language therapists",
    roleFamily: "Healthcare & Care",
    metaDescription: "Recruitment support for speech and language therapist hires, subject to appropriate professional registration.",
    overview: "Speech and language therapy roles require relevant professional registration and experience suited to the client group involved.",
    hiringChallenges: ["Verifying professional registration", "Specialist demand across education and healthcare settings"],
    skillsSought: ["Relevant professional registration", "Client-group-specific clinical experience", "Collaborative multidisciplinary working"],
    recruitmentApproach: "Recruitment process includes registration verification alongside relevant clinical experience review.",
    relatedSectorSlugs: ["hr-company-for-healthcare-in-the-uk", "hr-company-for-education-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("speech and language therapists")],
  },
  {
    slug: "clinical-psychologists",
    title: "Clinical psychologists",
    roleFamily: "Healthcare & Care",
    metaDescription: "Recruitment support for clinical psychologist hires, subject to appropriate professional registration.",
    overview: "Clinical psychology roles require verified professional registration and experience relevant to the clinical setting.",
    hiringChallenges: ["Nationwide demand against a limited specialist pool", "Verifying registration and clinical specialism"],
    skillsSought: ["Relevant professional registration", "Clinical specialism appropriate to the role", "Strong assessment and reporting skill"],
    recruitmentApproach: "Search typically draws on relevant clinical networks alongside registration verification.",
    relatedSectorSlugs: ["hr-company-for-healthcare-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "executive-search-firm-in-the-uk"],
    faqs: [genericFaq("clinical psychologists")],
  },
  {
    slug: "psychologists",
    title: "Other psychologists",
    roleFamily: "Healthcare & Care",
    metaDescription: "Recruitment support for psychologist hires outside clinical practice, subject to appropriate professional registration.",
    overview: "This category covers psychologists working outside clinical settings, such as in occupational, educational or forensic contexts.",
    hiringChallenges: ["Verifying registration relevant to the specific specialism", "Varied settings requiring different experience profiles"],
    skillsSought: ["Relevant professional registration and specialism", "Setting-specific experience", "Strong analytical and reporting skills"],
    recruitmentApproach: "Assessment focuses on registration and specialism fit for the specific role and setting.",
    relatedSectorSlugs: ["hr-company-for-education-in-the-uk", "hr-company-for-professional-services-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("other psychologists")],
  },
  {
    slug: "medical-radiographers",
    title: "Medical radiographers",
    roleFamily: "Healthcare & Care",
    metaDescription: "Recruitment support for medical radiographer hires, subject to appropriate professional registration.",
    overview: "Radiographer roles require verified professional registration and hands-on experience with relevant imaging technology.",
    hiringChallenges: ["Sustained national demand for radiography talent", "Verifying registration and modality-specific experience"],
    skillsSought: ["Relevant professional registration", "Modality-specific technical experience", "Patient care and communication"],
    recruitmentApproach: "Recruitment process includes registration verification alongside modality-specific experience review.",
    relatedSectorSlugs: ["hr-company-for-healthcare-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("medical radiographers")],
  },
  {
    slug: "medical-dental-technicians",
    title: "Medical and dental technicians",
    roleFamily: "Healthcare & Care",
    metaDescription: "Recruitment support for medical and dental technician hires.",
    overview: "These technical roles require precise, hands-on skill and, often, relevant qualifications specific to the discipline.",
    hiringChallenges: ["Verifying technical qualifications and precision skill", "Specialist, often niche skill requirements"],
    skillsSought: ["Relevant technical qualifications", "Precision and attention to detail", "Familiarity with relevant equipment and materials"],
    recruitmentApproach: "Assessment focuses on technical qualification and hands-on skill relevant to the discipline.",
    relatedSectorSlugs: ["hr-company-for-healthcare-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("medical and dental technicians")],
  },
  {
    slug: "early-education-childcare-practitioners",
    title: "Early education and childcare practitioners",
    roleFamily: "Healthcare & Care",
    metaDescription: "Recruitment support for early education and childcare practitioner hires.",
    overview: "These roles require relevant qualifications, safeguarding checks and a genuine aptitude for working with young children.",
    hiringChallenges: ["Safeguarding and DBS check requirements", "Sector-wide recruitment and retention pressure"],
    skillsSought: ["Relevant early years qualifications", "Safeguarding awareness", "Genuine aptitude for working with young children"],
    recruitmentApproach: "Recruitment process incorporates relevant safeguarding checks alongside qualification verification.",
    relatedSectorSlugs: ["hr-company-for-education-in-the-uk", "hr-company-for-care-homes-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("early education and childcare practitioners")],
  },
  {
    slug: "veterinary-nurses",
    title: "Veterinary nurses",
    roleFamily: "Healthcare & Care",
    metaDescription: "Recruitment support for veterinary nurse hires, subject to appropriate professional registration.",
    overview: "Veterinary nursing roles require verified professional registration and hands-on clinical experience.",
    hiringChallenges: ["Verifying professional registration", "Sustained demand across the sector"],
    skillsSought: ["Relevant professional registration", "Clinical and animal-handling experience", "Client communication skills"],
    recruitmentApproach: "Recruitment process includes registration verification alongside clinical experience review.",
    relatedSectorSlugs: ["hr-company-for-healthcare-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("veterinary nurses")],
  },
  {
    slug: "senior-care-workers",
    title: "Senior care workers",
    roleFamily: "Healthcare & Care",
    metaDescription: "Recruitment support for senior care worker hires.",
    overview: "Senior care worker roles combine hands-on care experience with team coordination and mentoring responsibilities.",
    hiringChallenges: ["Sector-wide recruitment and retention pressure", "Verifying safeguarding and care-sector experience"],
    skillsSought: ["Relevant care qualifications and experience", "Team coordination and mentoring", "Safeguarding awareness"],
    recruitmentApproach: "Recruitment process incorporates relevant safeguarding checks alongside experience verification.",
    relatedSectorSlugs: ["hr-company-for-care-homes-in-the-uk", "hr-company-for-healthcare-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "recruitment-process-outsourcing-rpo-firm-in-the-uk"],
    faqs: [genericFaq("senior care workers")],
  },
  {
    slug: "houseparents-residential-wardens",
    title: "Houseparents and residential wardens",
    roleFamily: "Healthcare & Care",
    metaDescription: "Recruitment support for houseparent and residential warden hires.",
    overview: "These roles carry significant pastoral and safeguarding responsibility within residential settings.",
    hiringChallenges: ["Safeguarding and suitability checks", "Assessing pastoral capability alongside practical management skill"],
    skillsSought: ["Relevant safeguarding qualifications or checks", "Pastoral care experience", "Resilience and sound judgement"],
    recruitmentApproach: "Recruitment process incorporates thorough safeguarding checks alongside pastoral experience review.",
    relatedSectorSlugs: ["hr-company-for-education-in-the-uk", "hr-company-for-care-homes-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("houseparents and residential wardens")],
  },

  // --- Finance, tax & compliance ---
  {
    slug: "financial-accounting-technicians",
    title: "Financial and accounting technicians",
    roleFamily: "Finance & Compliance",
    metaDescription: "Recruitment support for financial and accounting technician hires.",
    overview: "These roles require solid technical accounting skill and, often, progress toward or completion of a relevant qualification.",
    hiringChallenges: ["Verifying qualification status and technical competence", "Competitive market for qualified and part-qualified staff"],
    skillsSought: ["Relevant accounting qualifications or progress toward them", "Technical accuracy and process discipline", "Systems and software familiarity"],
    recruitmentApproach: "Assessment includes qualification verification alongside a review of technical experience.",
    relatedSectorSlugs: ["hr-company-for-accountants-in-the-uk", "hr-company-for-professional-services-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("financial and accounting technicians")],
  },
  {
    slug: "credit-controllers",
    title: "Credit controllers",
    roleFamily: "Finance & Compliance",
    metaDescription: "Recruitment support for credit controller hires.",
    overview: "Credit control roles require a firm but constructive approach to collections, alongside strong process and communication skills.",
    hiringChallenges: ["Assessing negotiation skill alongside process discipline", "Sector-specific collections experience where relevant"],
    skillsSought: ["Credit control or collections experience", "Firm, professional communication", "Process and reconciliation accuracy"],
    recruitmentApproach: "Assessment focuses on relevant collections experience and evidence of effective, professional communication.",
    relatedSectorSlugs: ["hr-company-for-professional-services-in-the-uk", "hr-company-for-distribution-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("credit controllers")],
  },
  {
    slug: "bookkeepers-payroll-wages-clerks",
    title: "Book-keepers, payroll managers and wages clerks",
    roleFamily: "Finance & Compliance",
    metaDescription: "Recruitment support for bookkeeping, payroll and wages clerk hires.",
    overview: "These roles require accuracy and reliability given their direct impact on employee pay and financial records.",
    hiringChallenges: ["High accuracy requirements given payroll impact on employees", "Systems and software-specific experience"],
    skillsSought: ["Relevant bookkeeping or payroll experience", "Accuracy and attention to detail", "Systems and software familiarity"],
    recruitmentApproach: "Assessment includes review of relevant systems experience and evidence of accuracy under deadline pressure.",
    relatedSectorSlugs: ["hr-company-for-professional-services-in-the-uk", "hr-company-for-accountants-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "payroll-advisory-firm-in-the-uk"],
    faqs: [genericFaq("book-keepers, payroll managers and wages clerks")],
  },
  {
    slug: "taxation-experts",
    title: "Taxation experts",
    roleFamily: "Finance & Compliance",
    metaDescription: "Recruitment support for taxation expert hires.",
    overview: "Taxation roles require up-to-date technical knowledge and, typically, relevant professional qualifications.",
    hiringChallenges: ["Verifying relevant professional qualifications", "Keeping pace with a competitive, specialist market"],
    skillsSought: ["Relevant tax qualifications", "Specialism appropriate to the role (e.g. corporate, personal, VAT)", "Client or stakeholder communication"],
    recruitmentApproach: "Assessment includes qualification verification alongside specialism and client-facing experience.",
    relatedSectorSlugs: ["hr-company-for-accountants-in-the-uk", "hr-company-for-financial-services-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "executive-search-firm-in-the-uk"],
    faqs: [genericFaq("taxation experts")],
  },
  {
    slug: "estimators-valuers-assessors",
    title: "Estimators, valuers and assessors",
    roleFamily: "Finance & Compliance",
    metaDescription: "Recruitment support for estimator, valuer and assessor hires.",
    overview: "These roles require strong analytical judgement and, often, sector-specific technical knowledge to produce reliable estimates and valuations.",
    hiringChallenges: ["Sector-specific technical knowledge requirements", "Verifying relevant professional accreditation where applicable"],
    skillsSought: ["Relevant sector or technical experience", "Analytical and numerical accuracy", "Professional accreditation where applicable"],
    recruitmentApproach: "Assessment focuses on sector-relevant experience and evidence of accurate, defensible judgement.",
    relatedSectorSlugs: ["hr-company-for-construction-in-the-uk", "hr-company-for-architects-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("estimators, valuers and assessors")],
  },
  {
    slug: "standards-regulations-inspectors",
    title: "Inspectors of standards and regulations",
    roleFamily: "Finance & Compliance",
    metaDescription: "Recruitment support for standards and regulations inspector hires.",
    overview: "Inspector roles require strong attention to detail, independence and knowledge of the relevant regulatory framework.",
    hiringChallenges: ["Verifying relevant regulatory knowledge", "Assessing independence and objectivity"],
    skillsSought: ["Relevant regulatory or standards knowledge", "Independence and sound judgement", "Clear, evidence-based reporting"],
    recruitmentApproach: "Assessment focuses on relevant regulatory experience and evidence of objective, well-documented decision-making.",
    relatedSectorSlugs: ["hr-company-for-professional-services-in-the-uk", "hr-company-for-construction-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("inspectors of standards and regulations")],
  },

  // --- Engineering & technical trades ---
  {
    slug: "engineering-technicians",
    title: "Engineering technicians",
    roleFamily: "Engineering & Technical",
    metaDescription: "Recruitment support for engineering technician hires.",
    overview: "Engineering technician roles require hands-on technical skill and, often, discipline-specific qualifications.",
    hiringChallenges: ["Verifying discipline-specific technical competence", "Competitive market for skilled technical staff"],
    skillsSought: ["Relevant technical qualifications", "Discipline-specific hands-on experience", "Problem-solving under practical constraints"],
    recruitmentApproach: "Assessment includes technical screening relevant to the specific engineering discipline.",
    relatedSectorSlugs: ["hr-company-for-engineers-in-the-uk", "hr-company-for-manufacturers-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("engineering technicians")],
  },
  {
    slug: "quality-assurance-technicians",
    title: "Quality assurance technicians",
    roleFamily: "Engineering & Technical",
    metaDescription: "Recruitment support for quality assurance technician hires.",
    overview: "QA roles require methodical attention to detail and familiarity with relevant quality standards and processes.",
    hiringChallenges: ["Verifying relevant quality standards knowledge", "Assessing methodical, process-driven working style"],
    skillsSought: ["Relevant quality standards knowledge (e.g. ISO)", "Methodical, process-driven approach", "Reporting and documentation skill"],
    recruitmentApproach: "Assessment focuses on relevant quality-standards experience and evidence of process discipline.",
    relatedSectorSlugs: ["hr-company-for-manufacturers-in-the-uk", "hr-company-for-engineers-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("quality assurance technicians")],
  },
  {
    slug: "planning-process-production-technicians",
    title: "Planning, process and production technicians",
    roleFamily: "Engineering & Technical",
    metaDescription: "Recruitment support for planning, process and production technician hires.",
    overview: "These roles balance technical process knowledge with planning and scheduling responsibility in production environments.",
    hiringChallenges: ["Sector-specific process knowledge requirements", "Assessing planning and scheduling capability"],
    skillsSought: ["Relevant production or process experience", "Planning and scheduling skill", "Systems familiarity relevant to the environment"],
    recruitmentApproach: "Assessment focuses on relevant production-environment experience and planning capability.",
    relatedSectorSlugs: ["hr-company-for-manufacturers-in-the-uk", "hr-company-for-engineers-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("planning, process and production technicians")],
  },
  {
    slug: "cad-drawing-architectural-technicians",
    title: "CAD, drawing and architectural technicians",
    roleFamily: "Engineering & Technical",
    metaDescription: "Recruitment support for CAD, drawing and architectural technician hires.",
    overview: "These roles require strong technical drawing skill and familiarity with relevant CAD software packages.",
    hiringChallenges: ["Software-specific skill verification", "Assessing accuracy and technical drawing standards"],
    skillsSought: ["Relevant CAD software proficiency", "Technical drawing accuracy", "Familiarity with relevant industry standards"],
    recruitmentApproach: "Assessment includes review of a portfolio or work samples alongside software proficiency verification.",
    relatedSectorSlugs: ["hr-company-for-architects-in-the-uk", "hr-company-for-engineers-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("CAD, drawing and architectural technicians")],
  },
  {
    slug: "metalworking-production-maintenance-fitters",
    title: "Metal working production and maintenance fitters",
    roleFamily: "Engineering & Technical",
    metaDescription: "Recruitment support for metalworking production and maintenance fitter hires.",
    overview: "These skilled trade roles require verified technical competence and, often, relevant apprenticeship or trade qualifications.",
    hiringChallenges: ["Verifying trade qualifications and hands-on competence", "Sector-wide demand for skilled trades"],
    skillsSought: ["Relevant trade qualifications", "Hands-on fitting and maintenance experience", "Health and safety awareness"],
    recruitmentApproach: "Assessment includes qualification verification alongside practical, hands-on experience review.",
    relatedSectorSlugs: ["hr-company-for-manufacturers-in-the-uk", "hr-company-for-engineers-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("metal working production and maintenance fitters")],
  },
  {
    slug: "precision-instrument-makers-repairers",
    title: "Precision instrument makers and repairers",
    roleFamily: "Engineering & Technical",
    metaDescription: "Recruitment support for precision instrument maker and repairer hires.",
    overview: "These specialist roles require fine hand skill and precision, often built up over years of relevant training.",
    hiringChallenges: ["Small, specialist candidate pool", "Verifying precision craft skill"],
    skillsSought: ["Relevant precision craft training or experience", "Fine motor skill and attention to detail", "Patience for detailed, exacting work"],
    recruitmentApproach: "Search often draws on specialist trade networks given the niche nature of these skills.",
    relatedSectorSlugs: ["hr-company-for-manufacturers-in-the-uk", "hr-company-for-engineers-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("precision instrument makers and repairers")],
  },
  {
    slug: "security-system-installers-repairers",
    title: "Security system installers and repairers",
    roleFamily: "Engineering & Technical",
    metaDescription: "Recruitment support for security system installer and repairer hires.",
    overview: "These technical roles require relevant certification and hands-on installation experience, often with a customer-facing element.",
    hiringChallenges: ["Verifying relevant technical certification", "Assessing customer-facing communication alongside technical skill"],
    skillsSought: ["Relevant technical certification", "Installation and troubleshooting experience", "Customer-facing communication"],
    recruitmentApproach: "Assessment includes certification verification alongside practical installation experience review.",
    relatedSectorSlugs: ["hr-company-for-construction-in-the-uk", "hr-company-for-manufacturers-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("security system installers and repairers")],
  },
  {
    slug: "skilled-metal-electrical-electronic-trades-supervisors",
    title: "Skilled metal, electrical and electronic trades supervisors",
    roleFamily: "Engineering & Technical",
    metaDescription: "Recruitment support for skilled metal, electrical and electronic trades supervisor hires.",
    overview: "These roles combine hands-on trade credibility with supervisory responsibility for a wider technical team.",
    hiringChallenges: ["Assessing trade credibility alongside supervisory skill", "Sector-wide demand for experienced trade supervisors"],
    skillsSought: ["Relevant trade qualifications and experience", "Team supervision capability", "Health and safety leadership"],
    recruitmentApproach: "Assessment covers trade credibility and hands-on experience alongside evidence of supervisory capability.",
    relatedSectorSlugs: ["hr-company-for-manufacturers-in-the-uk", "hr-company-for-construction-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("skilled metal, electrical and electronic trades supervisors")],
  },
  {
    slug: "floorers-wall-tilers",
    title: "Floorers and wall tilers",
    roleFamily: "Engineering & Technical",
    metaDescription: "Recruitment support for floorer and wall tiler hires.",
    overview: "These skilled trade roles require verified hands-on competence and, often, relevant trade qualifications or experience.",
    hiringChallenges: ["Verifying practical trade competence", "Sector-wide demand for skilled trades"],
    skillsSought: ["Relevant trade experience or qualifications", "Precision and finish quality", "Reliability on site"],
    recruitmentApproach: "Assessment focuses on practical trade experience, often supported by references or work examples.",
    relatedSectorSlugs: ["hr-company-for-construction-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("floorers and wall tilers")],
  },
  {
    slug: "industrial-cleaning-process-occupations",
    title: "Industrial cleaning process occupations",
    roleFamily: "Engineering & Technical",
    metaDescription: "Recruitment support for industrial cleaning process role hires.",
    overview: "These roles require reliability and, in many settings, specific health, safety and hygiene training.",
    hiringChallenges: ["Shift-based and often high-volume resourcing needs", "Sector-specific hygiene or safety training requirements"],
    skillsSought: ["Relevant safety and hygiene training", "Reliability and attention to process", "Comfort with physically demanding work"],
    recruitmentApproach: "Recruitment can be structured for high-volume or shift-based resourcing where needed.",
    relatedSectorSlugs: ["hr-company-for-manufacturers-in-the-uk", "hr-company-for-distribution-in-the-uk"],
    relatedServiceSlugs: ["recruitment-process-outsourcing-rpo-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("industrial cleaning process occupations")],
  },

  // --- HR, training & careers guidance ---
  {
    slug: "human-resources-industrial-relations-officers",
    title: "Human resources and industrial relations officers",
    roleFamily: "HR & Training",
    metaDescription: "Recruitment support for HR and industrial relations officer hires.",
    overview: "These roles require solid HR generalist or employee-relations knowledge, often with sector-specific context.",
    hiringChallenges: ["Assessing depth of employee-relations experience", "Sector-specific HR context where relevant"],
    skillsSought: ["HR generalist or employee-relations experience", "Relevant HR qualifications (e.g. CIPD)", "Sound, practical judgement"],
    recruitmentApproach: "Assessment focuses on relevant HR experience and evidence of practical, well-judged decision-making.",
    relatedSectorSlugs: ["hr-company-for-professional-services-in-the-uk", "hr-company-for-manufacturers-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("human resources and industrial relations officers")],
  },
  {
    slug: "careers-advisers-vocational-guidance",
    title: "Careers advisers and vocational guidance specialists",
    roleFamily: "HR & Training",
    metaDescription: "Recruitment support for careers adviser and vocational guidance specialist hires.",
    overview: "These roles require strong interpersonal skill and up-to-date knowledge of relevant education and career pathways.",
    hiringChallenges: ["Assessing genuine advisory and coaching skill", "Keeping pace with changing career-pathway information"],
    skillsSought: ["Relevant careers guidance qualifications", "Strong interpersonal and coaching skill", "Up-to-date labour-market knowledge"],
    recruitmentApproach: "Assessment focuses on relevant guidance experience and evidence of effective, empathetic advisory skill.",
    relatedSectorSlugs: ["hr-company-for-education-in-the-uk", "hr-company-for-charity-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("careers advisers and vocational guidance specialists")],
  },
  {
    slug: "vocational-industrial-trainers",
    title: "Other vocational and industrial trainers",
    roleFamily: "HR & Training",
    metaDescription: "Recruitment support for vocational and industrial trainer hires.",
    overview: "These roles combine subject-matter expertise with the ability to design and deliver effective, practical training.",
    hiringChallenges: ["Combining technical expertise with training delivery skill", "Often project-based or fluctuating demand"],
    skillsSought: ["Relevant subject-matter expertise", "Training design and delivery experience", "Assessment and evaluation skill"],
    recruitmentApproach: "Assessment covers subject expertise alongside evidence of effective, practical training delivery.",
    relatedSectorSlugs: ["hr-company-for-manufacturers-in-the-uk", "hr-company-for-construction-in-the-uk"],
    relatedServiceSlugs: ["contract-staffing-firm-in-the-uk", "learning-strategy-and-capability-development-firm-in-the-uk"],
    faqs: [genericFaq("other vocational and industrial trainers")],
  },

  // --- Transport & logistics ---
  {
    slug: "aircraft-pilots-air-traffic-controllers",
    title: "Aircraft pilots and air traffic controllers",
    roleFamily: "Transport & Logistics",
    metaDescription: "Recruitment support for aircraft pilot and air traffic controller hires, subject to appropriate licensing.",
    overview: "These highly regulated roles require verified licensing and, typically, extensive relevant training and flight or control hours.",
    hiringChallenges: ["Strict licensing and regulatory verification requirements", "Small, highly specialised candidate pool"],
    skillsSought: ["Relevant licensing and regulatory approval", "Verified flight or control experience", "Rigorous safety discipline"],
    recruitmentApproach: "Recruitment process includes thorough licensing and regulatory verification alongside experience review.",
    relatedSectorSlugs: ["hr-company-for-distribution-in-the-uk"],
    relatedServiceSlugs: ["executive-search-firm-in-the-uk", "permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("aircraft pilots and air traffic controllers")],
  },
  {
    slug: "rail-travel-assistants",
    title: "Rail travel assistants",
    roleFamily: "Transport & Logistics",
    metaDescription: "Recruitment support for rail travel assistant hires.",
    overview: "These customer-facing roles require strong communication skill and, often, safety-related training specific to the rail environment.",
    hiringChallenges: ["Sector-specific safety training requirements", "Shift-based resourcing needs"],
    skillsSought: ["Relevant safety training or willingness to train", "Customer service skill", "Reliability in shift-based roles"],
    recruitmentApproach: "Recruitment process incorporates relevant safety-training requirements alongside customer-service assessment.",
    relatedSectorSlugs: ["hr-company-for-distribution-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "recruitment-process-outsourcing-rpo-firm-in-the-uk"],
    faqs: [genericFaq("rail travel assistants")],
  },
  {
    slug: "train-tram-drivers",
    title: "Train and tram drivers",
    roleFamily: "Transport & Logistics",
    metaDescription: "Recruitment support for train and tram driver hires, subject to appropriate licensing and training.",
    overview: "These roles require rigorous safety training and licensing specific to the relevant rail or tram network.",
    hiringChallenges: ["Extensive, network-specific training requirements", "Verifying licensing and safety-critical competence"],
    skillsSought: ["Relevant licensing or aptitude for network-specific training", "Rigorous safety discipline", "Concentration and reliability"],
    recruitmentApproach: "Recruitment process includes thorough safety and licensing verification alongside aptitude assessment.",
    relatedSectorSlugs: ["hr-company-for-distribution-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("train and tram drivers")],
  },

  // --- Retail, leisure & customer-facing ---
  {
    slug: "retail-cashiers-checkout-operators",
    title: "Retail cashiers and check-out operators",
    roleFamily: "Retail, Leisure & Customer-Facing",
    metaDescription: "Recruitment support for retail cashier and check-out operator hires.",
    overview: "These front-line roles require reliability, accuracy and strong customer-facing communication, often at volume.",
    hiringChallenges: ["High-volume, often seasonal resourcing needs", "Consistent customer-service standards across large teams"],
    skillsSought: ["Customer service orientation", "Accuracy handling transactions", "Reliability in shift-based roles"],
    recruitmentApproach: "Recruitment can be structured for high-volume or seasonal resourcing where needed.",
    relatedSectorSlugs: ["hr-company-for-hospitality-in-the-uk", "hr-company-for-leisure-in-the-uk"],
    relatedServiceSlugs: ["recruitment-process-outsourcing-rpo-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("retail cashiers and check-out operators")],
  },
  {
    slug: "leisure-theme-park-attendants",
    title: "Leisure and theme park attendants",
    roleFamily: "Retail, Leisure & Customer-Facing",
    metaDescription: "Recruitment support for leisure and theme park attendant hires.",
    overview: "These customer-facing, often seasonal roles require strong communication skill and reliability at operational scale.",
    hiringChallenges: ["Strong seasonal demand peaks", "Assessing customer-service aptitude at volume"],
    skillsSought: ["Customer service orientation", "Reliability in shift-based, seasonal roles", "Comfort with operational safety procedures"],
    recruitmentApproach: "Recruitment planning is typically built around known seasonal peaks in demand.",
    relatedSectorSlugs: ["hr-company-for-leisure-in-the-uk", "hr-company-for-hospitality-in-the-uk"],
    relatedServiceSlugs: ["recruitment-process-outsourcing-rpo-firm-in-the-uk"],
    faqs: [genericFaq("leisure and theme park attendants")],
  },
  {
    slug: "photographers-audiovisual-broadcasting-operators",
    title: "Photographers, audio-visual and broadcasting equipment operators",
    roleFamily: "Retail, Leisure & Customer-Facing",
    metaDescription: "Recruitment support for photographer, audio-visual and broadcasting equipment operator hires.",
    overview: "These technical, often creative roles require a strong portfolio and hands-on equipment experience relevant to the setting.",
    hiringChallenges: ["Assessing portfolio quality alongside technical skill", "Often project-based or freelance-adjacent resourcing"],
    skillsSought: ["Relevant equipment and technical experience", "Portfolio of previous work", "Adaptability across project types"],
    recruitmentApproach: "Assessment typically includes portfolio review alongside technical and equipment-specific discussion.",
    relatedSectorSlugs: ["hr-company-for-leisure-in-the-uk", "hr-company-for-professional-services-in-the-uk"],
    relatedServiceSlugs: ["contract-staffing-firm-in-the-uk", "permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("photographers, audio-visual and broadcasting equipment operators")],
  },
  {
    slug: "library-clerks-assistants",
    title: "Library clerks and assistants",
    roleFamily: "Retail, Leisure & Customer-Facing",
    metaDescription: "Recruitment support for library clerk and assistant hires.",
    overview: "These roles combine organisational accuracy with helpful, patient customer service in public-facing settings.",
    hiringChallenges: ["Assessing organisational accuracy alongside customer service", "Often part-time or flexible resourcing needs"],
    skillsSought: ["Organisational and cataloguing accuracy", "Customer service skill", "Comfort with relevant library systems"],
    recruitmentApproach: "Assessment focuses on organisational accuracy and customer-facing communication skill.",
    relatedSectorSlugs: ["hr-company-for-education-in-the-uk", "hr-company-for-charity-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk"],
    faqs: [genericFaq("library clerks and assistants")],
  },

  // --- Agriculture & environment ---
  {
    slug: "farm-workers",
    title: "Farm workers",
    roleFamily: "Agriculture & Environment",
    metaDescription: "Recruitment support for farm worker hires.",
    overview: "Farm worker roles are often physically demanding and, particularly at peak times, subject to significant seasonal demand.",
    skillsSought: ["Relevant practical or agricultural experience", "Reliability in physically demanding, outdoor roles", "Comfort with seasonal working patterns"],
    hiringChallenges: ["Strong seasonal demand peaks", "Physically demanding role requirements"],
    recruitmentApproach: "Recruitment planning is typically built around known seasonal peaks in agricultural demand.",
    relatedSectorSlugs: ["hr-company-for-manufacturers-in-the-uk"],
    relatedServiceSlugs: ["recruitment-process-outsourcing-rpo-firm-in-the-uk", "contract-staffing-firm-in-the-uk"],
    faqs: [genericFaq("farm workers")],
  },
  {
    slug: "environment-professionals",
    title: "Environment professionals",
    roleFamily: "Agriculture & Environment",
    metaDescription: "Recruitment support for environment professional hires.",
    overview: "Environment professional roles increasingly span regulatory compliance, sustainability strategy and technical environmental assessment.",
    hiringChallenges: ["Growing demand against a still-developing talent pool", "Verifying relevant technical or regulatory expertise"],
    skillsSought: ["Relevant environmental qualifications", "Regulatory and compliance knowledge", "Technical or sustainability-strategy experience"],
    recruitmentApproach: "Assessment focuses on relevant technical and regulatory experience for the specific role.",
    relatedSectorSlugs: ["hr-company-for-life-sciences-in-the-uk", "hr-company-for-manufacturers-in-the-uk"],
    relatedServiceSlugs: ["permanent-recruitment-firm-in-the-uk", "executive-search-firm-in-the-uk"],
    faqs: [genericFaq("environment professionals")],
  },
];
